=== nothairyyq/Data-Science-XJTLU/CPT201TC/Week3 Lab/Lab2/company.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="dnoType">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="1"/>
    <xs:maxInclusive value="50"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="ssnType">
  <xs:restriction base="xs:string">
    <xs:pattern value="[0-9]{9}"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="listOfSSNType">
  <xs:list itemType="ssnType"/>
</xs:simpleType>

<xs:simpleType name="pnoType">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="1"/>
    <xs:maxInclusive value="200"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="hoursType">
  <xs:restriction base="xs:decimal">
    <xs:totalDigits value="5"/>
    <xs:fractionDigits value="2"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="listOfPnoType">
  <xs:list itemType="pnoType"/>
</xs:simpleType>

<xs:complexType name="locationsType">
  <xs:sequence>
    <xs:element name="location" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="managerType">
  <xs:sequence>
    <xs:element name="startDate" type="xs:string"/>
  </xs:sequence>
  <xs:attribute name="mssn" type="ssnType"/>
</xs:complexType>

<xs:complexType name="ssnListType">
  <xs:attribute name="essns" type="listOfSSNType"/>
</xs:complexType>

<xs:complexType name="pnoListType">
  <xs:attribute name="pnos" type="listOfPnoType"/>
</xs:complexType>

<xs:complexType name="departmentType">
  <xs:sequence>
    <xs:element name="dname" type="xs:string"/>
    <xs:element name="locations" type="locationsType"/>
    <xs:element name="manager" type="managerType"/>
    <xs:element name="employees" type="ssnListType"/>
    <xs:element name="projectsControlled" type="pnoListType"/>
  </xs:sequence>
  <xs:attribute name="dno" type="dnoType" use="required"/>
</xs:complexType>

<xs:complexType name="departmentsType">
  <xs:sequence>
    <xs:element name="department" type="departmentType" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<xs:simpleType name="genderType">
   <xs:restriction base="xs:string">
      <xs:enumeration value="M"/>
      <xs:enumeration value="F"/>
   </xs:restriction>
</xs:simpleType>

<xs:simpleType name="salaryType">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="1000"/>
    <xs:maxInclusive value="200000"/>
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="dependentsType">
  <xs:sequence>
    <xs:element name="dependent" type="dependentType" minOccurs="1" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="dependentType">
  <xs:sequence>
    <xs:element name="dependentName" type="xs:string"/>
    <xs:element name="sex" type="genderType"/>
    <xs:element name="dob" type="xs:string"/>
    <xs:element name="relationship" type="xs:string"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="prjsType">
  <xs:sequence>
    <xs:element name="worksOn" type="prjType" minOccurs="1" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="prjType">
  <xs:attribute name="pno" type="pnoType" use="required"/>
  <xs:attribute name="hours" type="hoursType" use="required"/>
</xs:complexType>

<xs:complexType name="employeeType">
  <xs:sequence>
    <xs:element name="fname" type="xs:string"/>
    <xs:element name="minit" type="xs:string"/>
    <xs:element name="lname" type="xs:string"/>
    <xs:element name="dob" type="xs:string"/>
    <xs:element name="address" type="xs:string"/>
    <xs:element name="sex" type="genderType"/>
    <xs:element name="salary" type="salaryType"/>
    <xs:element name="dependents" type="dependentsType" minOccurs="0"/>
    <xs:element name="supervisees" type="ssnListType" minOccurs="0"/>
    <xs:element name="projects" type="prjsType" minOccurs="0"/>
  </xs:sequence>
  <xs:attribute name="ssn" type="ssnType" use="required"/>
  <xs:attribute name="worksFor" type="dnoType" use="required"/>
  <xs:attribute name="supervisor" type="ssnType"/>
  <xs:attribute name="manages" type="dnoType"/>
</xs:complexType>

<xs:complexType name="employeesType">
  <xs:sequence>
    <xs:element name="employee" type="employeeType" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="workersType">
  <xs:sequence>
    <xs:element name="worker" type="workerType" minOccurs="1" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="workerType">
  <xs:simpleContent>
    <xs:extension base="hoursType">
      <xs:attribute name="essn" type="ssnType"/>
    </xs:extension>
  </xs:simpleContent>
</xs:complexType>

<xs:complexType name="projectType">
  <xs:sequence>
    <xs:element name="pname" type="xs:string"/>
    <xs:element name="plocation" type="xs:string"/>
    <xs:element name="workers" type="workersType" minOccurs="0"/>
  </xs:sequence>
  <xs:attribute name="pnumber" type="pnoType" use="required"/>
  <xs:attribute name="controllingDepartment" type="dnoType" use="required"/>
</xs:complexType>

<xs:complexType name="projectsType">
  <xs:sequence>
    <xs:element name="project" type="projectType" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="companyDBType">
  <xs:sequence>
    <xs:element name="departments" type="departmentsType"/>
    <xs:element name="employees" type="employeesType"/>
    <xs:element name="projects" type="projectsType"/>
  </xs:sequence>
</xs:complexType>

<xs:element name="companyDB" type="companyDBType"/>

</xs:schema>

=== nothairyyq/Data-Science-XJTLU/CPT201TC/Week3 Lab/Lab2/company.xml
<?xml version="1.0" ?>
<companyDB xsi:noNamespaceSchemaLocation="company.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <departments>
  
    <department dno="1">
      <dname>Headquarters</dname>
      <locations>
        <location>Houston</location>
      </locations>
      <manager mssn="888665555">
        <startDate>19-JUN-1971</startDate>
      </manager>
      <employees essns="888665555"/>
      <projectsControlled pnos="20"/>
    </department>
  
    <department dno="4">
      <dname>Administration</dname>
      <locations>
        <location>Stafford</location>
      </locations>
      <manager mssn="987654321">
        <startDate>01-JAN-1985</startDate>
      </manager>
      <employees essns="987654321 987987987 999887777"/>
      <projectsControlled pnos="10 30"/>
    </department>
  
    <department dno="5">
      <dname>Research</dname>
      <locations>
        <location>Bellaire</location>
        <location>Sugarland</location>
        <location>Houston</location>
      </locations>
      <manager mssn="333445555">
        <startDate>22-MAY-1978</startDate>
      </manager>
      <employees essns="123456789 333445555 666884444 453453453"/>
      <projectsControlled pnos="1 2 3"/>
    </department>
  
    <department dno="6">
      <dname>Software</dname>
      <locations>
        <location>Atlanta</location>
        <location>Sacramento</location>
      </locations>
      <manager mssn="111111100">
        <startDate>15-MAY-1999</startDate>
      </manager>
      <employees essns="111111100 555555500 111111101 111111102 111111103 333333300 333333301 555555501"/>
      <projectsControlled pnos="61 62 63"/>
    </department>
  
    <department dno="7">
      <dname>Hardware</dname>
      <locations>
        <location>Milwaukee</location>
      </locations>
      <manager mssn="444444400">
        <startDate>15-MAY-1998</startDate>
      </manager>
      <employees essns="222222200 222222201 222222202 222222203 222222204 222222205 444444400 444444401 444444402 444444403"/>
      <projectsControlled pnos="91 92"/>
    </department>
  
    <department dno="8">
      <dname>Sales</dname>
      <locations>
        <location>Chicago</location>
        <location>Dallas</location>
        <location>Philadelphia</location>
        <location>Seattle</location>
        <location>Miami</location>
      </locations>
      <manager mssn="555555500">
        <startDate>01-JAN-1997</startDate>
      </manager>
      <employees essns="666666600 666666601 666666602 666666603 666666604 666666605 666666606 666666607 666666608 666666609 666666610 666666611 666666612 666666613"/>
      <projectsControlled pnos=""/>
    </department>
  
  </departments>

  <employees>

    <employee ssn="333445555" worksFor="5" supervisor="888665555" manages="5">
      <fname>Franklin</fname>
      <minit>T</minit>
      <lname>Wong</lname>
      <dob>08-DEC-45</dob>
      <address>638 Voss, Houston, TX</address>
      <sex>M</sex>
      <salary>40000</salary>
      <dependents>
        <dependent>
          <dependentName>Alice</dependentName>
          <sex>F</sex>
          <dob>05-APR-1976</dob>
          <relationship>Daughter</relationship>
        </dependent>
        <dependent>
          <dependentName>Theodore</dependentName>
          <sex>M</sex>
          <dob>25-OCT-1973</dob>
          <relationship>Son</relationship>
        </dependent>
        <dependent>
          <dependentName>Joy</dependentName>
          <sex>F</sex>
          <dob>03-MAY-1948</dob>
          <relationship>Spouse</relationship>
        </dependent>
      </dependents>
      <supervisees essns="123456789 666884444 453453453"/>
      <projects>
        <worksOn pno="2" hours="10.0"/>
        <worksOn pno="3" hours="10.0"/>
        <worksOn pno="10" hours="10.0"/>
        <worksOn pno="20" hours="10.0"/>
      </projects>
    </employee>

    <employee ssn="888665555" worksFor="1" manages="1">
      <fname>James</fname>
      <minit>E</minit>
      <lname>Borg</lname>
      <dob>10-NOV-27</dob>
      <address>450 Stone, Houston, TX</address>
      <sex>M</sex>
      <salary>55000</salary>
      <supervisees essns="333445555 987654321"/>
      <projects>
        <worksOn pno="20" hours="0.0"/>
      </projects>
    </employee>

    <employee ssn="987654321" worksFor="4" supervisor="888665555" manages="4">
      <fname>Jennifer</fname>
      <minit>S</minit>
      <lname>Wallace</lname>
      <dob>20-JUN-31</dob>
      <address>291 Berry, Bellaire, TX</address>
      <sex>F</sex>
      <salary>43000</salary>
      <dependents>
        <dependent>
          <dependentName>Abner</dependentName>
          <sex>M</sex>
          <dob>29-FEB-1932</dob>
          <relationship>Spouse</relationship>
        </dependent>
      </dependents>
      <supervisees essns="999887777 987987987"/>
      <projects>
        <worksOn pno="30" hours="20.0"/>
        <worksOn pno="20" hours="15.0"/>
      </projects>
    </employee>

    <employee ssn="123456789" worksFor="5" supervisor="333445555">
      <fname>John</fname>
      <minit>B</minit>
      <lname>Smith</lname>
      <dob>09-Jan-55</dob>
      <address>731 Fondren, Houston, TX</address>
      <sex>M</sex>
      <salary>30000</salary>
      <dependents>
        <dependent>
          <dependentName>Michael</dependentName>
          <sex>M</sex>
          <dob>01-JAN-1978</dob>
          <relationship>Son</relationship>
        </dependent>
        <dependent>
          <dependentName>Alice</dependentName>
          <sex>F</sex>
          <dob>31-DEC-1978</dob>
          <relationship>Daughter</relationship>
        </dependent>
        <dependent>
          <dependentName>Elizabeth</dependentName>
          <sex>F</sex>
          <dob>05-MAY-1957</dob>
          <relationship>Spouse</relationship>
        </dependent>
      </dependents>
      <projects>
        <worksOn pno="1" hours="32.5"/>
        <worksOn pno="2" hours="7.5"/>
      </projects>
    </employee>

    <employee ssn="999887777" worksFor="4" supervisor="987654321">
      <fname>Alicia</fname>
      <minit>J</minit>
      <lname>Zelaya</lname>
      <dob>19-JUL-58</dob>
      <address>3321 Castle, Spring, TX</address>
      <sex>F</sex>
      <salary>25000</salary>
      <projects>
        <worksOn pno="30" hours="30.0"/>
        <worksOn pno="10" hours="10.0"/>
      </projects>
    </employee>

    <employee ssn="666884444" worksFor="5" supervisor="333445555">
      <fname>Ramesh</fname>
      <minit>K</minit>
      <lname>Narayan</lname>
      <dob>15-SEP-52</dob>
      <address>971 Fire Oak, Humble, TX</address>
      <sex>M</sex>
      <salary>38000</salary>
      <projects>
        <worksOn pno="3" hours="40.0"/>
      </projects>
    </employee>

    <employee ssn="453453453" worksFor="5" supervisor="333445555">
      <fname>Joyce</fname>
      <minit>A</minit>
      <lname>English</lname>
      <dob>31-JUL-62</dob>
      <address>5631 Rice, Houston, TX</address>
      <sex>F</sex>
      <salary>25000</salary>
      <projects>
        <worksOn pno="1" hours="20.0"/>
        <worksOn pno="2" hours="20.0"/>
      </projects>
    </employee>

    <employee ssn="987987987" worksFor="4" supervisor="987654321">
      <fname>Ahmad</fname>
      <minit>V</minit>
      <lname>Jabbar</lname>
      <dob>29-MAR-59</dob>
      <address>980 Dallas, Houston, TX</address>
      <sex>M</sex>
      <salary>25000</salary>
      <projects>
        <worksOn pno="10" hours="35.0"/>
        <worksOn pno="30" hours="5.0"/>
      </projects>
    </employee>

    <employee ssn="111111100" worksFor="6" manages="6">
      <fname>Jared</fname>
      <minit>D</minit>
      <lname>James</lname>
      <dob>10-OCT-1966</dob>
      <address>123 Peachtree, Atlanta, GA</address>
      <sex>M</sex>
      <salary>85000</salary>
      <supervisees essns="111111101 111111102 111111103"/>
      <projects>
        <worksOn pno="61" hours="40.0"/>
      </projects>
    </employee>

    <employee ssn="444444400" worksFor="7" manages="7">
      <fname>Alex</fname>
      <minit>D</minit>
      <lname>Freed</lname>
      <dob>09-OCT-1950</dob>
      <address>4333 Pillsbury, Milwaukee, WI</address>
      <sex>M</sex>
      <salary>89000</salary>
      <dependents>
        <dependent>
          <dependentName>Johnny</dependentName>
          <sex>M</sex>
          <dob>04-APR-1997</dob>
          <relationship>Son</relationship>
        </dependent>
        <dependent>
          <dependentName>Tommy</dependentName>
          <sex>M</sex>
          <dob>07-APR-1999</dob>
          <relationship>Son</relationship>
        </dependent>
      </dependents>
      <supervisees essns="444444401 444444402 444444403"/>
      <projects>
        <worksOn pno="91" hours="40.0"/>
      </projects>
    </employee>

    <employee ssn="555555500" worksFor="6" manages="8">
      <fname>John</fname>
      <minit>C</minit>
      <lname>James</lname>
      <dob>30-JUN-1975</dob>
      <address>7676 Bloomington, Sacramento, CA</address>
      <sex>M</sex>
      <salary>81000</salary>
      <supervisees essns="555555501"/>
      <projects>
        <worksOn pno="92" hours="40.0"/>
      </projects>
    </employee>

    <employee ssn="111111101" worksFor="6" supervisor="111111100">
      <fname>Jon</fname>
      <minit>C</minit>
      <lname>Jones</lname>
      <dob>14-NOV-1967</dob>
      <address>111 Allgood, Atlanta, GA</address>
      <sex>M</sex>
      <salary>45000</salary>
      <projects>
        <worksOn pno="61" hours="40.0"/>
      </projects>
    </employee>

    <employee ssn="111111102" worksFor="6" supervisor="111111100">
      <fname>Justin</fname>
